apiVersion: v1
kind: Pod
metadata:
    name: flask-app-pod-bueno
    labels:
        name: service-ip-cluster
spec:
    containers:
        - name: flask-app
          image: alanbzez20/ejemplo:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
                path: /health
                port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3