apiVersion: v1
kind: Service
metadata:
    name: service-ip-cluster
spec:
    type: ClusterIP
    selector:
        app: service-ip-cluster
    ports:
        - protocol: TCP
          port: 8080
          target-port: 8080